name: Build LaTeX PDF and Upload Artifact

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex

      - name: Create deployment folder and copy PDF
        run: |
          mkdir -p deploy
          cp main.pdf deploy/

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: latex-pdf
          path: deploy/main.pdf
